all: cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4
cyoa-step1: cyoa-step1.cpp story.h page.h
	g++ -ggdb3 -o cyoa-step1 -Wall -Werror --std=gnu++03 cyoa-step1.cpp
cyoa-step2: cyoa-step2.cpp story.h page.h
	g++ -ggdb3 -o cyoa-step2 -Wall -Werror --std=gnu++03 cyoa-step2.cpp
cyoa-step3: cyoa-step3.cpp story.h page.h
	g++ -ggdb3 -o cyoa-step3 -Wall -Werror --std=gnu++03 cyoa-step3.cpp
cyoa-step4: cyoa-step4.cpp story-step4.h page-step4.h
	g++ -ggdb3 -o cyoa-step4 -Wall -Werror --std=gnu++03 cyoa-step4.cpp
